paths:
    raw_data_dirs: ["/home/tf/Documents/Image_Understanding_project/Self-Supervised-Endoscopic-Image-Key-Points-Matching/data/HighCam/Colon-IV/TumorfreeTrajectory_1/frame",]
    export_dir: "/home/tf/Documents/Image_Understanding_project/Self-Supervised-Endoscopic-Image-Key-Points-Matching/data/train_dataset/HighCam/Colon-IV"
params:
    keypoint_extractor: "SIFT"
    # distance in pixel
    keypoint_dist_threshold: 5
    patch_size: 64
    transformation_list: ['zoom', 'rotation', 'translation']
    predefined_angle_degrees: [5, 10, 15]
    predefined_zoom_factors: [0.9, 0.95, 1.05, 1.1, 1.15]
    predefined_translation_pixels: [8]
